### ISSUE TITLE
Suggestions for scraping 

### ISSUE THREAD

**Issue by dskvr** [sesseor/nostr-relays-list#1]
Be sure you're scraping the following:

1. `kind:2` 
2. `kind:3` 
3. `kind:10002`

Also consider that some of those relays have been offline for more than a year (likely dead forever) 

Compare your results to mine and let me know when you've surpassed me, I'm too bogged down to focus on this right now! 

https://api.nostr.watch/v1/online
https://api.nostr.watch/v1/offline 

I am curious how you handled the new `runonflux` relays. Are you programmatically filtering or by manually filtering them? 

Also, please check out NIP-66 if, like me, you're interested in this stuff: https://github.com/nostr-protocol/nips/pull/230

**Comment by sesseor** [comment]
i just created a script like a day ago to scrap and filter
i will probably do kind 2 too 
idk what runonflux is but i will take a look

**Comment by dskvr** [comment]
`runonflux` has some subdomains `nostr1234556.app.runonflux.com` and I suspect they have implemented pay-to-relay in subdomains, which is inconvenient.

**Comment by gourcetools** [comment]
You may be able to discovers relays by getting "prefered relay, default relay or relays" from profile metadata.
